.TH gbirthday 1  "12/2/2010" "0.6.5" "gbirthday Man Page"
.SH NAME
.B gbirthday 
-  a birthday reminder application that helps you to remember your contacts' birthdays
.SH OPTIONS
.B gbirthday
does not have parameters for the command line interface.
.SH DESCRIPTION
.B gbirthday 
is a birthday reminder application that helps you to remember your contacts' birthdays.
It can be used with Evolution Contacts, CVS files, MySQL databases, Thunderbird/Icedove Lightning and Sunbird/Iceowl events. Notification of upcoming and today's birthdays is done via the GNOME notification area.
.SH VERSION
.SH AUTHORS
This man page has been written for
.B gbirthday
version 0.6.5 by Braulio Valdivielso Martínez <brlvldvlsmrtnz@gmail.com> with some modifications by Rolf Leggewie.
